import type { RawCatalogSource } from "./types.ts";

const capturedAt = "2026-05-23T00:00:00.000Z";

export const mockRawCatalogSources: RawCatalogSource[] = [
  {
    id: "raw_source_historical_quote_2026_001",
    source_type: "historical_quote",
    source_name: "2026 Q1 住宅裝修歷史報價節錄",
    source_owner: "laibe_budget_ops",
    source_date: "2026-03-15",
    captured_at: capturedAt,
    region: "TW-TPE",
    currency: "TWD",
    source_note: "內部回填的歷史報價節錄，僅供候選資料審核。",
    source_reliability: "medium",
    metadata: {
      document_type: "historical_quote_excerpt",
    },
    raw_items: [
      {
        id: "raw_item_hq_001",
        source_id: "raw_source_historical_quote_2026_001",
        row_index: 1,
        raw_category: "木作工程",
        raw_name: "中島吧檯矮櫃",
        raw_brand: null,
        raw_model: null,
        raw_spec: "E1 系統板",
        raw_unit: "尺",
        raw_quantity: 6,
        raw_unit_price: 3500,
        raw_amount: 21000,
        raw_currency: "TWD",
        raw_note: "不含人造石及設備",
        raw_text: "中島吧檯矮櫃 / 尺 / 3500 / 不含人造石及設備",
        effective_date: "2026-03-15",
        region: "TW-TPE",
        vendor_name: "歷史案件 A",
        metadata: {},
      },
      {
        id: "raw_item_hq_002",
        source_id: "raw_source_historical_quote_2026_001",
        row_index: 2,
        raw_category: "泥作工程",
        raw_name: "浴室壁磚貼工",
        raw_brand: null,
        raw_model: null,
        raw_spec: "30x60",
        raw_unit: "式",
        raw_quantity: 1,
        raw_unit_price: 18000,
        raw_amount: 18000,
        raw_currency: "TWD",
        raw_note: "不含磁磚材料",
        raw_text: "浴室壁磚貼工 / 式 / 18000 / 不含磁磚材料",
        effective_date: "2026-03-15",
        region: "TW-TPE",
        vendor_name: "歷史案件 A",
        metadata: {},
      },
      {
        id: "raw_item_hq_003",
        source_id: "raw_source_historical_quote_2026_001",
        row_index: 3,
        raw_category: "水電工程",
        raw_name: "插座出口延伸",
        raw_brand: null,
        raw_model: null,
        raw_spec: null,
        raw_unit: "口",
        raw_quantity: 8,
        raw_unit_price: 1800,
        raw_amount: 14400,
        raw_currency: "TWD",
        raw_note: "依現場管線調整",
        raw_text: "插座出口延伸 / 口 / 1800 / 依現場管線調整",
        effective_date: "2026-03-15",
        region: "TW-TPE",
        vendor_name: "歷史案件 A",
        metadata: {},
      },
    ],
  },
  {
    id: "raw_source_material_sheet_2026_001",
    source_type: "material_price_sheet",
    source_name: "常用材料觀測價目表",
    source_owner: "laibe_procurement",
    source_date: "2026-04-01",
    captured_at: capturedAt,
    region: "TW-TPE",
    currency: "TWD",
    source_note: "材料觀測價，不代表正式材料規格或正式價格。",
    source_reliability: "medium",
    metadata: {
      document_type: "material_price_sheet",
    },
    raw_items: [
      {
        id: "raw_item_mat_001",
        source_id: "raw_source_material_sheet_2026_001",
        row_index: 1,
        raw_category: "板材",
        raw_name: "E1 系統櫃板材",
        raw_brand: null,
        raw_model: null,
        raw_spec: "E1 等級",
        raw_unit: "片",
        raw_quantity: null,
        raw_unit_price: 1600,
        raw_amount: null,
        raw_currency: "TWD",
        raw_note: "依厚度與表面材調整",
        raw_text: "E1 系統櫃板材 / 片 / 1600 / 依厚度與表面材調整",
        effective_date: "2026-04-01",
        region: "TW-TPE",
        vendor_name: "材料供應商 M",
        metadata: {},
      },
      {
        id: "raw_item_mat_002",
        source_id: "raw_source_material_sheet_2026_001",
        row_index: 2,
        raw_category: "檯面",
        raw_name: "韓國人造石",
        raw_brand: "KR Stone",
        raw_model: null,
        raw_spec: "標準色",
        raw_unit: "CM",
        raw_quantity: null,
        raw_unit_price: 180,
        raw_amount: null,
        raw_currency: "TWD",
        raw_note: "依選材調整",
        raw_text: "韓國人造石 / CM / 180 / 依選材調整",
        effective_date: "2026-04-01",
        region: "TW-TPE",
        vendor_name: "材料供應商 M",
        metadata: {},
      },
      {
        id: "raw_item_mat_003",
        source_id: "raw_source_material_sheet_2026_001",
        row_index: 3,
        raw_category: "防水",
        raw_name: "彈性水泥",
        raw_brand: null,
        raw_model: null,
        raw_spec: "防水材料",
        raw_unit: "桶",
        raw_quantity: null,
        raw_unit_price: 950,
        raw_amount: null,
        raw_currency: "TWD",
        raw_note: "批次價格差異大",
        raw_text: "彈性水泥 / 桶 / 950 / 批次價格差異大",
        effective_date: "2026-04-01",
        region: "TW-TPE",
        vendor_name: "材料供應商 M",
        metadata: {},
      },
    ],
  },
  {
    id: "raw_source_vendor_quote_2026_001",
    source_type: "vendor_quote",
    source_name: "磁磚供應商報價節錄",
    source_owner: "laibe_procurement",
    source_date: "2026-04-12",
    captured_at: capturedAt,
    region: "TW-TPE",
    currency: "TWD",
    source_note: "廠商報價觀測，不可直接當正式價格。",
    source_reliability: "high",
    metadata: {
      vendor_name: "Tile Vendor A",
    },
    raw_items: [
      {
        id: "raw_item_vendor_001",
        source_id: "raw_source_vendor_quote_2026_001",
        row_index: 1,
        raw_category: "磁磚",
        raw_name: "30x60 壁磚",
        raw_brand: "TileCo",
        raw_model: "TC-W3060",
        raw_spec: "30x60 霧面",
        raw_unit: "箱",
        raw_quantity: 20,
        raw_unit_price: 1280,
        raw_amount: 25600,
        raw_currency: "TWD",
        raw_note: "不含運費與損耗",
        raw_text: "30x60 壁磚 / 箱 / 1280 / 不含運費與損耗",
        effective_date: "2026-04-12",
        region: "TW-TPE",
        vendor_name: "Tile Vendor A",
        metadata: {},
      },
      {
        id: "raw_item_vendor_002",
        source_id: "raw_source_vendor_quote_2026_001",
        row_index: 2,
        raw_category: "磁磚",
        raw_name: "30x60 地磚",
        raw_brand: "TileCo",
        raw_model: "TC-F3060",
        raw_spec: "30x60 防滑",
        raw_unit: null,
        raw_quantity: 10,
        raw_unit_price: 1380,
        raw_amount: 13800,
        raw_currency: "TWD",
        raw_note: "原始列缺少單位，需人工補齊",
        raw_text: "30x60 地磚 / 1380 / 原始列缺少單位",
        effective_date: "2026-04-12",
        region: "TW-TPE",
        vendor_name: "Tile Vendor A",
        metadata: {},
      },
    ],
  },
  {
    id: "raw_source_market_reference_2026_001",
    source_type: "market_price_reference",
    source_name: "市場價格人工記錄",
    source_owner: "laibe_procurement",
    source_date: "2026-04-20",
    captured_at: capturedAt,
    region: "TW-TPE",
    currency: "TWD",
    source_note: "人工紀錄的市場觀測資料，不爬網、不自動採信。",
    source_reliability: "low",
    metadata: {
      capture_method: "manual",
    },
    raw_items: [
      {
        id: "raw_item_market_001",
        source_id: "raw_source_market_reference_2026_001",
        row_index: 1,
        raw_category: "燈具",
        raw_name: "LED 崁燈",
        raw_brand: null,
        raw_model: null,
        raw_spec: "9W 白光",
        raw_unit: "盞",
        raw_quantity: null,
        raw_unit_price: 650,
        raw_amount: null,
        raw_currency: "TWD",
        raw_note: "市場觀測價，不含安裝",
        raw_text: "LED 崁燈 / 盞 / 650 / 市場觀測價，不含安裝",
        effective_date: "2026-04-20",
        region: "TW-TPE",
        vendor_name: null,
        metadata: {},
      },
    ],
  },
  {
    id: "raw_source_brand_model_2026_001",
    source_type: "brand_model_catalog",
    source_name: "衛浴品牌型號候選表",
    source_owner: "laibe_procurement",
    source_date: "2026-04-25",
    captured_at: capturedAt,
    region: "TW-TPE",
    currency: "TWD",
    source_note: "品牌型號候選，不含正式採購價。",
    source_reliability: "medium",
    metadata: {},
    raw_items: [
      {
        id: "raw_item_brand_001",
        source_id: "raw_source_brand_model_2026_001",
        row_index: 1,
        raw_category: "衛浴設備",
        raw_name: "TOTO 馬桶",
        raw_brand: "TOTO",
        raw_model: "CW-001",
        raw_spec: "標準單體馬桶",
        raw_unit: "組",
        raw_quantity: null,
        raw_unit_price: null,
        raw_amount: null,
        raw_currency: "TWD",
        raw_note: "僅品牌型號候選，不含正式價格",
        raw_text: "TOTO 馬桶 / CW-001 / 標準單體馬桶",
        effective_date: "2026-04-25",
        region: "TW-TPE",
        vendor_name: null,
        metadata: {},
      },
    ],
  },
  {
    id: "raw_source_labor_rate_2026_001",
    source_type: "labor_rate_sheet",
    source_name: "人工單價觀測表",
    source_owner: "laibe_budget_ops",
    source_date: "2026-04-28",
    captured_at: capturedAt,
    region: "TW-TPE",
    currency: "TWD",
    source_note: "人工觀測價，需後續審核才可成為正式 LaborRule。",
    source_reliability: "medium",
    metadata: {},
    raw_items: [
      {
        id: "raw_item_labor_001",
        source_id: "raw_source_labor_rate_2026_001",
        row_index: 1,
        raw_category: "木作人工",
        raw_name: "木工師傅",
        raw_brand: null,
        raw_model: null,
        raw_spec: "日工",
        raw_unit: "工",
        raw_quantity: null,
        raw_unit_price: 3500,
        raw_amount: null,
        raw_currency: "TWD",
        raw_note: "依地區與案件複雜度調整",
        raw_text: "木工師傅 / 工 / 3500 / 依地區與案件複雜度調整",
        effective_date: "2026-04-28",
        region: "TW-TPE",
        vendor_name: null,
        metadata: {},
      },
      {
        id: "raw_item_labor_002",
        source_id: "raw_source_labor_rate_2026_001",
        row_index: 2,
        raw_category: "泥作人工",
        raw_name: "泥作貼磚工",
        raw_brand: null,
        raw_model: null,
        raw_spec: "牆地磚貼工",
        raw_unit: "m2",
        raw_quantity: null,
        raw_unit_price: 1800,
        raw_amount: null,
        raw_currency: "TWD",
        raw_note: "依磚材尺寸與現場條件調整",
        raw_text: "泥作貼磚工 / m2 / 1800 / 依磚材尺寸與現場條件調整",
        effective_date: "2026-04-28",
        region: "TW-TPE",
        vendor_name: null,
        metadata: {},
      },
    ],
  },
  {
    id: "raw_source_note_sheet_2026_001",
    source_type: "note_sheet",
    source_name: "工法備註候選句",
    source_owner: "laibe_budget_ops",
    source_date: "2026-05-01",
    captured_at: capturedAt,
    region: "TW-TPE",
    currency: "TWD",
    source_note: "備註候選，不含價格。",
    source_reliability: "high",
    metadata: {},
    raw_items: [
      {
        id: "raw_item_note_001",
        source_id: "raw_source_note_sheet_2026_001",
        row_index: 1,
        raw_category: "備註",
        raw_name: "浴室防水高度以 H:240 估算",
        raw_brand: null,
        raw_model: null,
        raw_spec: null,
        raw_unit: null,
        raw_quantity: null,
        raw_unit_price: null,
        raw_amount: null,
        raw_currency: null,
        raw_note: "工法備註候選",
        raw_text: "浴室防水高度以 H:240 估算",
        effective_date: "2026-05-01",
        region: "TW-TPE",
        vendor_name: null,
        metadata: {},
      },
      {
        id: "raw_item_note_002",
        source_id: "raw_source_note_sheet_2026_001",
        row_index: 2,
        raw_category: "不明",
        raw_name: "",
        raw_brand: null,
        raw_model: null,
        raw_spec: null,
        raw_unit: null,
        raw_quantity: null,
        raw_unit_price: null,
        raw_amount: null,
        raw_currency: null,
        raw_note: "掃描結果無法辨識",
        raw_text: "",
        effective_date: null,
        region: "TW-TPE",
        vendor_name: null,
        metadata: {
          parse_error: true,
        },
      },
    ],
  },
];
