import type { BudgetOutputSnapshot } from "../output/types.ts";

export const fixtureBudgetOutputSnapshot: BudgetOutputSnapshot = {
  snapshot_id: "snapshot_fixture_output_001",
  estimate_id: "estimate_fixture_001",
  project_id: "project_fixture_budget_output",
  estimate_stage: "mock",
  output_version: "budget-output-v1",
  generated_at: "2026-05-23T00:00:00.000Z",
  catalog_version: "method-spec-fixture-v1",
  customer_view: [
    {
      trade_category: "保護工程",
      subtotal: 15000,
      lines: [
        {
          trade_category: "保護工程",
          line_no: "1",
          item_name: "保護工程",
          unit: "式",
          quantity: 1,
          unit_price: 15000,
          amount: 15000,
          customer_note: "依現場範圍調整",
        },
      ],
    },
    {
      trade_category: "木作工程",
      subtotal: 21000,
      lines: [
        {
          trade_category: "木作工程",
          line_no: "1",
          item_name: "中島吧檯矮櫃",
          unit: "尺",
          quantity: 6,
          unit_price: 3500,
          amount: 21000,
          customer_note: "不含人造石及設備",
        },
      ],
    },
  ],
  internal_view: [
    {
      trade_category: "保護工程",
      subtotal: 15000,
      lines: [
        {
          trade_category: "保護工程",
          line_no: "1",
          item_code: "SITE_PROTECTION",
          item_name: "保護工程",
          unit: "式",
          quantity: 1,
          unit_price: 15000,
          amount: 15000,
          customer_note: "依現場範圍調整",
          internal_note: "Fixture snapshot line; no material binding required.",
          source_type: "project",
          source_id: "project_fixture_budget_output",
          recipe_id: "recipe_project_overhead",
          material_code: null,
          quantity_formula: "1",
          price_source: {
            type: "fixture_snapshot",
            id: "fixture_pricing_site_protection",
            label: "Fixture pricing only",
          },
          confidence: 0.9,
          requires_review: false,
          inclusions: ["現場公共區域基礎保護"],
          exclusions: ["特殊高風險保護另計"],
          assumptions: ["以一般住宅現場估算"],
          risks: [],
        },
      ],
    },
    {
      trade_category: "木作工程",
      subtotal: 21000,
      lines: [
        {
          trade_category: "木作工程",
          line_no: "1",
          item_code: "KITCHEN_ISLAND_BASE_CABINET",
          item_name: "中島吧檯矮櫃",
          unit: "尺",
          quantity: 6,
          unit_price: 3500,
          amount: 21000,
          customer_note: "不含人造石及設備",
          internal_note: "Fixture snapshot line; material spec is reference only.",
          source_type: "layout_object",
          source_id: "layout_fixture_kitchen_island",
          recipe_id: "recipe_kitchen_island_base_cabinet",
          material_code: "PANEL_E1_STANDARD",
          quantity_formula: "width_cm / 30.3",
          price_source: {
            type: "fixture_snapshot",
            id: "fixture_pricing_kitchen_island_base",
            label: "Fixture pricing only",
          },
          confidence: 0.86,
          requires_review: false,
          inclusions: ["中島矮櫃桶身"],
          exclusions: ["人造石檯面", "設備", "五金升級"],
          assumptions: ["寬度以 181.8cm 換算 6 尺"],
          risks: ["材料規格正式報價前需人工確認"],
        },
      ],
    },
  ],
  totals: {
    total_amount: 36000,
    customer_line_count: 2,
    internal_line_count: 2,
    trade_group_count: 2,
    review_required_count: 0,
  },
  validation_report: {
    valid: true,
    errors: [],
    warnings: [],
  },
  warnings: [
    "Fixture internal warning: source_id layout_fixture_kitchen_island recipe_id recipe_kitchen_island_base_cabinet quantity_formula width_cm / 30.3 material_code PANEL_E1_STANDARD.",
  ],
  source_summary: {
    estimate_line_count: 2,
    customer_line_count: 2,
    internal_line_count: 2,
    review_required_count: 0,
    material_linked_line_count: 1,
    material_unlinked_line_count: 1,
  },
};
