import type {
  MethodRecipe,
  PricingRule,
  QuoteItemTemplate,
} from "../types.ts";
import type {
  InclusionExclusionRule,
  ItemMaterialBinding,
  LaborRule,
  MaterialSpec,
  MethodSpecCatalog,
  NoteTemplate,
  UnitConversion,
} from "./types.ts";

const priceSource = (id: string, label: string) => ({
  type: "approved_method_spec_catalog",
  id,
  label,
});

export const METHOD_SPEC_ITEM_CODES = {
  islandCabinet: "WOOD_ISLAND_BASE_CABINET",
  islandCountertop: "WOOD_ISLAND_ARTIFICIAL_STONE_COUNTERTOP",
  wardrobeBody: "WOOD_WARDROBE_BODY",
  shoeCabinetBody: "WOOD_SHOE_CABINET_BODY",
  bathroomWaterproof: "BATHROOM_WATERPROOF_H240",
  bathroomWallTileLabor: "BATHROOM_WALL_TILE_LABOR",
  bathroomFloorTileLabor: "BATHROOM_FLOOR_TILE_LABOR",
  socketExtension: "ELECTRIC_SOCKET_EXTENSION",
  lightingInstall: "ELECTRIC_LIGHTING_INSTALL",
  protection: "OTHER_PROTECTION_WORK",
  cleaning: "OTHER_CLEANING_WORK",
  managementFee: "OTHER_MANAGEMENT_FEE",
} as const;

const quoteItemTemplates: QuoteItemTemplate[] = [
  {
    id: "qit-wood-island-cabinet",
    item_code: METHOD_SPEC_ITEM_CODES.islandCabinet,
    trade_code: "woodwork",
    engineering_category: "木作工程",
    item_name: "中島吧檯矮櫃",
    unit: "尺",
    default_notes: "中島矮櫃不含人造石及設備",
  },
  {
    id: "qit-wood-island-countertop",
    item_code: METHOD_SPEC_ITEM_CODES.islandCountertop,
    trade_code: "woodwork",
    engineering_category: "木作工程",
    item_name: "中島吧檯人造石檯面",
    unit: "CM",
    default_notes: "人造石檯面依選材調整",
  },
  {
    id: "qit-wood-wardrobe-body",
    item_code: METHOD_SPEC_ITEM_CODES.wardrobeBody,
    trade_code: "woodwork",
    engineering_category: "木作工程",
    item_name: "衣櫃桶身",
    unit: "尺",
    default_notes: "系統櫃板材以 E1 等級估算",
  },
  {
    id: "qit-wood-shoe-cabinet-body",
    item_code: METHOD_SPEC_ITEM_CODES.shoeCabinetBody,
    trade_code: "woodwork",
    engineering_category: "木作工程",
    item_name: "鞋櫃桶身",
    unit: "尺",
    default_notes: "系統櫃板材以 E1 等級估算",
  },
  {
    id: "qit-masonry-bath-waterproof-h240",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWaterproof,
    trade_code: "masonry",
    engineering_category: "泥作工程",
    item_name: "浴室彈性水泥防水 H:240",
    unit: "間",
    default_notes: "浴室防水高度以 H:240 估算",
  },
  {
    id: "qit-masonry-bath-wall-tile-labor",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWallTileLabor,
    trade_code: "masonry",
    engineering_category: "泥作工程",
    item_name: "浴室壁磚貼工",
    unit: "式",
    default_notes: "磁磚貼工不含磁磚材料",
  },
  {
    id: "qit-masonry-bath-floor-tile-labor",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomFloorTileLabor,
    trade_code: "masonry",
    engineering_category: "泥作工程",
    item_name: "浴室地磚貼工",
    unit: "式",
    default_notes: "磁磚貼工不含磁磚材料",
  },
  {
    id: "qit-mep-socket-extension",
    item_code: METHOD_SPEC_ITEM_CODES.socketExtension,
    trade_code: "mep",
    engineering_category: "水電工程",
    item_name: "插座出口延伸",
    unit: "口",
    default_notes: "插座出口延伸依現場管線調整",
  },
  {
    id: "qit-mep-lighting-install",
    item_code: METHOD_SPEC_ITEM_CODES.lightingInstall,
    trade_code: "mep",
    engineering_category: "水電工程",
    item_name: "燈具出線及安裝",
    unit: "盞",
    default_notes: "燈具出線及安裝不含燈具本體",
  },
  {
    id: "qit-other-protection",
    item_code: METHOD_SPEC_ITEM_CODES.protection,
    trade_code: "other",
    engineering_category: "其他",
    item_name: "保護工程",
    unit: "式",
    default_notes: "保護工程依現場範圍調整",
  },
  {
    id: "qit-other-cleaning",
    item_code: METHOD_SPEC_ITEM_CODES.cleaning,
    trade_code: "other",
    engineering_category: "其他",
    item_name: "清潔工程",
    unit: "式",
    default_notes: "清潔工程依完工狀態調整",
  },
  {
    id: "qit-other-management-fee",
    item_code: METHOD_SPEC_ITEM_CODES.managementFee,
    trade_code: "other",
    engineering_category: "其他",
    item_name: "工程管理費",
    unit: "式",
    default_notes: "工程管理費以總工程款百分比計算",
  },
];

const methodRecipes: MethodRecipe[] = [
  {
    recipe_id: "recipe-kitchen-island-basic",
    recipe_code: "RECIPE_KITCHEN_ISLAND_BASIC",
    recipe_name: "中島吧檯基本木作配方",
    version: "1.0.0-approved-spec",
    trigger_type: "layout_object",
    object_type: "kitchen_island",
    engineering_category: "木作工程",
    required_quantity_facts: [
      "kitchen_island_length_chi",
      "kitchen_island_width_cm",
    ],
    required_params: ["has_countertop"],
    outputs: [
      {
        quote_item_template_id: "qit-wood-island-cabinet",
        item_code: METHOD_SPEC_ITEM_CODES.islandCabinet,
        quantity_fact_type: "kitchen_island_length_chi",
        unit: "尺",
        quantity_formula: "width_cm / 30.3",
      },
      {
        quote_item_template_id: "qit-wood-island-countertop",
        item_code: METHOD_SPEC_ITEM_CODES.islandCountertop,
        quantity_fact_type: "kitchen_island_width_cm",
        unit: "CM",
        quantity_formula: "width_cm",
        condition: {
          param: "has_countertop",
          equals: true,
        },
      },
    ],
    default_assumptions: [
      "中島矮櫃不含人造石及設備",
      "人造石檯面依選材調整",
    ],
    review_triggers: ["missing_has_countertop", "special_countertop_material"],
  },
  {
    recipe_id: "recipe-wardrobe-standard",
    recipe_code: "RECIPE_WARDROBE_STANDARD",
    recipe_name: "衣櫃桶身標準配方",
    version: "1.0.0-approved-spec",
    trigger_type: "layout_object",
    object_type: "wardrobe",
    engineering_category: "木作工程",
    required_quantity_facts: ["wardrobe_length_chi"],
    required_params: [],
    outputs: [
      {
        quote_item_template_id: "qit-wood-wardrobe-body",
        item_code: METHOD_SPEC_ITEM_CODES.wardrobeBody,
        quantity_fact_type: "wardrobe_length_chi",
        unit: "尺",
        quantity_formula: "width_cm / 30.3",
      },
    ],
    default_assumptions: ["系統櫃板材以 E1 等級估算"],
    review_triggers: ["missing_finish_grade", "special_door_hardware"],
  },
  {
    recipe_id: "recipe-shoe-cabinet-standard",
    recipe_code: "RECIPE_SHOE_CABINET_STANDARD",
    recipe_name: "鞋櫃桶身標準配方",
    version: "1.0.0-approved-spec",
    trigger_type: "layout_object",
    object_type: "shoe_cabinet",
    engineering_category: "木作工程",
    required_quantity_facts: ["shoe_cabinet_length_chi"],
    required_params: [],
    outputs: [
      {
        quote_item_template_id: "qit-wood-shoe-cabinet-body",
        item_code: METHOD_SPEC_ITEM_CODES.shoeCabinetBody,
        quantity_fact_type: "shoe_cabinet_length_chi",
        unit: "尺",
        quantity_formula: "width_cm / 30.3",
      },
    ],
    default_assumptions: ["系統櫃板材以 E1 等級估算"],
    review_triggers: ["missing_finish_grade", "special_ventilation_detail"],
  },
  {
    recipe_id: "recipe-bathroom-basic",
    recipe_code: "RECIPE_BATHROOM_BASIC",
    recipe_name: "浴室防水與貼磚基本配方",
    version: "1.0.0-approved-spec",
    trigger_type: "space_group",
    space_type: "bathroom",
    engineering_category: "泥作工程",
    required_quantity_facts: ["bathroom_count"],
    required_params: [],
    outputs: [
      {
        quote_item_template_id: "qit-masonry-bath-waterproof-h240",
        item_code: METHOD_SPEC_ITEM_CODES.bathroomWaterproof,
        quantity_fact_type: "bathroom_count",
        unit: "間",
        quantity_formula: "count(space where space_type === 'bathroom')",
      },
      {
        quote_item_template_id: "qit-masonry-bath-wall-tile-labor",
        item_code: METHOD_SPEC_ITEM_CODES.bathroomWallTileLabor,
        quantity_fact_type: "bathroom_count",
        unit: "式",
        quantity_formula:
          "count(space where space_type === 'bathroom') * mock_wall_tile_scope_per_bathroom",
        review_reason: "壁磚貼工目前仍以每間浴室一式估算，需人工確認實際壁面面積。",
      },
      {
        quote_item_template_id: "qit-masonry-bath-floor-tile-labor",
        item_code: METHOD_SPEC_ITEM_CODES.bathroomFloorTileLabor,
        quantity_fact_type: "bathroom_count",
        unit: "式",
        quantity_formula:
          "count(space where space_type === 'bathroom') * mock_floor_tile_scope_per_bathroom",
        review_reason: "地磚貼工目前仍以每間浴室一式估算，需人工確認實際地坪面積。",
      },
    ],
    default_assumptions: [
      "浴室防水高度以 H:240 估算",
      "磁磚貼工不含磁磚材料",
    ],
    review_triggers: ["missing_tile_size", "missing_tile_area", "special_pattern"],
  },
  {
    recipe_id: "recipe-lighting-point-install",
    recipe_code: "RECIPE_LIGHTING_POINT_INSTALL",
    recipe_name: "燈具點位出線與安裝配方",
    version: "1.0.0-approved-spec",
    trigger_type: "layout_object_group",
    object_type: "lighting_point",
    engineering_category: "水電工程",
    required_quantity_facts: ["lighting_point_count"],
    required_params: [],
    outputs: [
      {
        quote_item_template_id: "qit-mep-lighting-install",
        item_code: METHOD_SPEC_ITEM_CODES.lightingInstall,
        quantity_fact_type: "lighting_point_count",
        unit: "盞",
        quantity_formula:
          "count(layout_object where object_type === 'lighting_point')",
      },
    ],
    default_assumptions: ["燈具出線及安裝不含燈具本體"],
    review_triggers: ["special_fixture", "unknown_circuit_condition"],
  },
  {
    recipe_id: "recipe-socket-point-extension",
    recipe_code: "RECIPE_SOCKET_POINT_EXTENSION",
    recipe_name: "插座出口延伸配方",
    version: "1.0.0-approved-spec",
    trigger_type: "layout_object_group",
    object_type: "socket_point",
    engineering_category: "水電工程",
    required_quantity_facts: ["socket_point_count"],
    required_params: [],
    outputs: [
      {
        quote_item_template_id: "qit-mep-socket-extension",
        item_code: METHOD_SPEC_ITEM_CODES.socketExtension,
        quantity_fact_type: "socket_point_count",
        unit: "口",
        quantity_formula:
          "count(layout_object where object_type === 'socket_point')",
      },
    ],
    default_assumptions: ["插座出口延伸依現場管線調整"],
    review_triggers: ["unknown_circuit_condition", "panel_capacity_review"],
  },
  {
    recipe_id: "recipe-project-general-costs",
    recipe_code: "RECIPE_PROJECT_GENERAL_COSTS",
    recipe_name: "專案一般費用配方",
    version: "1.0.0-approved-spec",
    trigger_type: "project",
    engineering_category: "其他",
    required_quantity_facts: ["project_lump_sum_count"],
    required_params: [],
    outputs: [
      {
        quote_item_template_id: "qit-other-protection",
        item_code: METHOD_SPEC_ITEM_CODES.protection,
        quantity_fact_type: "project_lump_sum_count",
        unit: "式",
        quantity_formula: "1 project lump sum",
        review_reason: "保護工程需依現場範圍確認。",
      },
      {
        quote_item_template_id: "qit-other-cleaning",
        item_code: METHOD_SPEC_ITEM_CODES.cleaning,
        quantity_fact_type: "project_lump_sum_count",
        unit: "式",
        quantity_formula: "1 project lump sum",
        review_reason: "清潔工程需依完工狀態確認。",
      },
      {
        quote_item_template_id: "qit-other-management-fee",
        item_code: METHOD_SPEC_ITEM_CODES.managementFee,
        quantity_fact_type: "project_lump_sum_count",
        unit: "式",
        quantity_formula: "subtotal_before_management_fee * 0.08",
        review_reason: "工程管理費以總工程款百分比計算，需確認專案管理範圍。",
      },
    ],
    default_assumptions: [
      "保護工程依現場範圍調整",
      "清潔工程依完工狀態調整",
      "工程管理費以總工程款百分比計算",
    ],
    review_triggers: ["unknown_site_condition", "unknown_project_duration"],
  },
];

const materialSpecs: MaterialSpec[] = [
  {
    material_code: "PANEL_E1_STANDARD",
    material_name: "E1 系統櫃板材",
    category: "cabinet_board",
    brand: null,
    grade: "standard",
    unit: "尺",
    customer_note: "系統櫃板材以 E1 等級估算",
    internal_note: "Phase 2.7 approved spec placeholder; vendor and exact board series pending.",
    is_active: true,
  },
  {
    material_code: "STONE_ARTIFICIAL_KR",
    material_name: "韓國人造石",
    category: "countertop",
    brand: "KR",
    grade: "standard",
    unit: "CM",
    customer_note: "人造石檯面依選材調整",
    internal_note: "Countertop material spec remains selectable and should be reviewed before formal quote.",
    is_active: true,
  },
  {
    material_code: "WATERPROOF_CEMENT",
    material_name: "彈性水泥",
    category: "waterproofing_material",
    brand: null,
    grade: "standard",
    unit: "間",
    customer_note: "浴室防水高度以 H:240 估算",
    internal_note: "Waterproofing scope is currently bathroom-count based.",
    is_active: true,
  },
  {
    material_code: "TILE_30X60_WALL",
    material_name: "30x60 壁磚",
    category: "tile",
    brand: null,
    grade: "standard",
    unit: "式",
    customer_note: "磁磚貼工不含磁磚材料",
    internal_note: "Tile material remains excluded from tile labor lines.",
    is_active: true,
  },
  {
    material_code: "TILE_30X60_FLOOR",
    material_name: "30x60 地磚",
    category: "tile",
    brand: null,
    grade: "standard",
    unit: "式",
    customer_note: "磁磚貼工不含磁磚材料",
    internal_note: "Tile material remains excluded from tile labor lines.",
    is_active: true,
  },
  {
    material_code: "SITE_PROTECTION_STANDARD",
    material_name: "標準保護材料",
    category: "protection_material",
    brand: null,
    grade: "standard",
    unit: "式",
    customer_note: "保護工程依現場範圍調整",
    internal_note: "Protection scope requires site review.",
    is_active: true,
  },
];

const laborRules: LaborRule[] = [
  {
    labor_code: "LABOR_WOOD_CABINET_STANDARD",
    labor_name: "木作櫃體標準人工規則",
    trade_category: "woodwork",
    unit: "尺",
    base_rate: 1200,
    customer_note: "木作人工已納入對應工項單價規則",
    internal_note: "Reference labor rule only; current engine uses PricingRule unit price.",
    is_active: true,
  },
  {
    labor_code: "LABOR_COUNTERTOP_INSTALL_STANDARD",
    labor_name: "人造石檯面安裝人工規則",
    trade_category: "woodwork",
    unit: "CM",
    base_rate: 40,
    customer_note: "人造石檯面依選材調整",
    internal_note: "Reference labor component for future split material/labor pricing.",
    is_active: true,
  },
  {
    labor_code: "LABOR_MASONRY_WATERPROOF_STANDARD",
    labor_name: "浴室防水標準人工規則",
    trade_category: "masonry",
    unit: "間",
    base_rate: 6000,
    customer_note: "浴室防水高度以 H:240 估算",
    internal_note: "Bathroom-count basis remains a Phase 2.7 mock simplification.",
    is_active: true,
  },
  {
    labor_code: "LABOR_TILE_LAYING_LUMP_SUM",
    labor_name: "浴室磁磚貼工一式人工規則",
    trade_category: "masonry",
    unit: "式",
    base_rate: 8000,
    customer_note: "磁磚貼工不含磁磚材料",
    internal_note: "Area-based tile labor should replace lump sum in a later phase.",
    is_active: true,
  },
  {
    labor_code: "LABOR_MEP_POINT_STANDARD",
    labor_name: "水電點位標準人工規則",
    trade_category: "mep",
    unit: "點",
    base_rate: 600,
    customer_note: "水電點位依現場管線調整",
    internal_note: "Lighting and socket lines still use separate PricingRule units.",
    is_active: true,
  },
  {
    labor_code: "LABOR_GENERAL_SITE_STANDARD",
    labor_name: "一般現場工程人工規則",
    trade_category: "other",
    unit: "式",
    base_rate: 0,
    customer_note: "一般工程依現場範圍調整",
    internal_note: "Placeholder for protection, cleaning, and management scope.",
    is_active: true,
  },
];

const noteTemplates: NoteTemplate[] = [
  {
    note_code: "NOTE_ISLAND_CABINET_EXCLUDES_COUNTERTOP_EQUIPMENT",
    note_type: "exclusion",
    trade_category: "woodwork",
    text: "中島矮櫃不含人造石及設備",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.islandCabinet],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_COUNTERTOP_SELECTION_REVIEW",
    note_type: "customer_note",
    trade_category: "woodwork",
    text: "人造石檯面依選材調整",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.islandCountertop],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_E1_BOARD_ASSUMPTION",
    note_type: "assumption",
    trade_category: "woodwork",
    text: "系統櫃板材以 E1 等級估算",
    applies_to_item_codes: [
      METHOD_SPEC_ITEM_CODES.wardrobeBody,
      METHOD_SPEC_ITEM_CODES.shoeCabinetBody,
    ],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_BATH_WATERPROOF_H240",
    note_type: "assumption",
    trade_category: "masonry",
    text: "浴室防水高度以 H:240 估算",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.bathroomWaterproof],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_TILE_LABOR_EXCLUDES_TILE_MATERIAL",
    note_type: "exclusion",
    trade_category: "masonry",
    text: "磁磚貼工不含磁磚材料",
    applies_to_item_codes: [
      METHOD_SPEC_ITEM_CODES.bathroomWallTileLabor,
      METHOD_SPEC_ITEM_CODES.bathroomFloorTileLabor,
    ],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_SOCKET_SITE_CONDITION",
    note_type: "risk",
    trade_category: "mep",
    text: "插座出口延伸依現場管線調整",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.socketExtension],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_LIGHTING_EXCLUDES_FIXTURE",
    note_type: "exclusion",
    trade_category: "mep",
    text: "燈具出線及安裝不含燈具本體",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.lightingInstall],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_PROTECTION_SITE_SCOPE",
    note_type: "risk",
    trade_category: "other",
    text: "保護工程依現場範圍調整",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.protection],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_CLEANING_COMPLETION_CONDITION",
    note_type: "risk",
    trade_category: "other",
    text: "清潔工程依完工狀態調整",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.cleaning],
    is_customer_visible: true,
    is_active: true,
  },
  {
    note_code: "NOTE_MANAGEMENT_PERCENTAGE",
    note_type: "assumption",
    trade_category: "other",
    text: "工程管理費以總工程款百分比計算",
    applies_to_item_codes: [METHOD_SPEC_ITEM_CODES.managementFee],
    is_customer_visible: true,
    is_active: true,
  },
];

const unitConversions: UnitConversion[] = [
  {
    from_unit: "cm",
    to_unit: "尺",
    factor: 1 / 30.3,
    formula_note: "cm / 30.3",
  },
  {
    from_unit: "m2",
    to_unit: "坪",
    factor: 1 / 3.305785,
    formula_note: "m2 / 3.305785",
  },
  {
    from_unit: "mm",
    to_unit: "cm",
    factor: 0.1,
    formula_note: "mm * 0.1",
  },
];

const inclusionExclusionRules: InclusionExclusionRule[] = [
  {
    rule_code: "IE_WOOD_ISLAND_BASE_CABINET",
    item_code: METHOD_SPEC_ITEM_CODES.islandCabinet,
    includes: ["中島吧檯矮櫃桶身", "標準五金"],
    excludes: ["人造石檯面", "水槽", "電器設備"],
    assumption: "以標準 E1 系統櫃板材估算。",
    requires_review: false,
  },
  {
    rule_code: "IE_WOOD_ISLAND_COUNTERTOP",
    item_code: METHOD_SPEC_ITEM_CODES.islandCountertop,
    includes: ["人造石檯面"],
    excludes: ["特殊造型加工", "水槽與設備"],
    assumption: "人造石檯面依選材調整。",
    requires_review: true,
  },
  {
    rule_code: "IE_WOOD_WARDROBE_BODY",
    item_code: METHOD_SPEC_ITEM_CODES.wardrobeBody,
    includes: ["衣櫃桶身", "標準板材"],
    excludes: ["特殊門片", "特殊五金"],
    assumption: "系統櫃板材以 E1 等級估算。",
    requires_review: false,
  },
  {
    rule_code: "IE_WOOD_SHOE_CABINET_BODY",
    item_code: METHOD_SPEC_ITEM_CODES.shoeCabinetBody,
    includes: ["鞋櫃桶身", "標準板材"],
    excludes: ["特殊通風件", "特殊五金"],
    assumption: "系統櫃板材以 E1 等級估算。",
    requires_review: false,
  },
  {
    rule_code: "IE_BATHROOM_WATERPROOF_H240",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWaterproof,
    includes: ["彈性水泥防水", "H:240 高度估算"],
    excludes: ["結構修補", "漏水責任判定"],
    assumption: "浴室防水高度以 H:240 估算。",
    requires_review: true,
  },
  {
    rule_code: "IE_BATHROOM_WALL_TILE_LABOR",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWallTileLabor,
    includes: ["壁磚貼工"],
    excludes: ["磁磚材料", "特殊拼花", "拆除"],
    assumption: "壁磚貼工目前以每間浴室一式估算。",
    requires_review: true,
  },
  {
    rule_code: "IE_BATHROOM_FLOOR_TILE_LABOR",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomFloorTileLabor,
    includes: ["地磚貼工"],
    excludes: ["磁磚材料", "特殊拼花", "拆除"],
    assumption: "地磚貼工目前以每間浴室一式估算。",
    requires_review: true,
  },
  {
    rule_code: "IE_ELECTRIC_SOCKET_EXTENSION",
    item_code: METHOD_SPEC_ITEM_CODES.socketExtension,
    includes: ["插座出口延伸"],
    excludes: ["總電盤擴充", "特殊拉線"],
    assumption: "插座出口延伸依現場管線調整。",
    requires_review: true,
  },
  {
    rule_code: "IE_ELECTRIC_LIGHTING_INSTALL",
    item_code: METHOD_SPEC_ITEM_CODES.lightingInstall,
    includes: ["燈具出線", "基本安裝"],
    excludes: ["燈具本體", "特殊吊掛結構"],
    assumption: "燈具出線及安裝不含燈具本體。",
    requires_review: false,
  },
  {
    rule_code: "IE_OTHER_PROTECTION",
    item_code: METHOD_SPEC_ITEM_CODES.protection,
    includes: ["現場基本保護"],
    excludes: ["特殊高風險保護", "搬運動線特別保護"],
    assumption: "保護工程依現場範圍調整。",
    requires_review: true,
  },
  {
    rule_code: "IE_OTHER_CLEANING",
    item_code: METHOD_SPEC_ITEM_CODES.cleaning,
    includes: ["完工基本清潔"],
    excludes: ["細清", "特殊污染清除"],
    assumption: "清潔工程依完工狀態調整。",
    requires_review: true,
  },
  {
    rule_code: "IE_OTHER_MANAGEMENT_FEE",
    item_code: METHOD_SPEC_ITEM_CODES.managementFee,
    includes: ["專案管理協調"],
    excludes: ["正式監造責任", "合約外追加管理"],
    assumption: "工程管理費以總工程款百分比計算。",
    requires_review: true,
  },
];

const itemMaterialBindings: ItemMaterialBinding[] = [
  {
    binding_code: "BIND_WOOD_ISLAND_BASE_CABINET_PANEL_E1",
    item_code: METHOD_SPEC_ITEM_CODES.islandCabinet,
    material_code: "PANEL_E1_STANDARD",
    role: "primary",
    is_default: true,
    requires_review: false,
    note: "Reference spec for island base cabinet board; does not change pricing.",
  },
  {
    binding_code: "BIND_WOOD_WARDROBE_BODY_PANEL_E1",
    item_code: METHOD_SPEC_ITEM_CODES.wardrobeBody,
    material_code: "PANEL_E1_STANDARD",
    role: "primary",
    is_default: true,
    requires_review: false,
    note: "Reference spec for wardrobe body board; does not change pricing.",
  },
  {
    binding_code: "BIND_WOOD_SHOE_CABINET_BODY_PANEL_E1",
    item_code: METHOD_SPEC_ITEM_CODES.shoeCabinetBody,
    material_code: "PANEL_E1_STANDARD",
    role: "primary",
    is_default: true,
    requires_review: false,
    note: "Reference spec for shoe cabinet body board; does not change pricing.",
  },
  {
    binding_code: "BIND_WOOD_ISLAND_COUNTERTOP_STONE_KR",
    item_code: METHOD_SPEC_ITEM_CODES.islandCountertop,
    material_code: "STONE_ARTIFICIAL_KR",
    role: "primary",
    is_default: true,
    requires_review: true,
    note: "Countertop material selection requires review; binding is traceability only.",
  },
  {
    binding_code: "BIND_BATHROOM_WATERPROOF_CEMENT",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWaterproof,
    material_code: "WATERPROOF_CEMENT",
    role: "primary",
    is_default: true,
    requires_review: false,
    note: "Waterproofing material spec reference; does not change pricing.",
  },
  {
    binding_code: "BIND_BATHROOM_WALL_TILE_30X60",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWallTileLabor,
    material_code: "TILE_30X60_WALL",
    role: "primary",
    is_default: true,
    requires_review: true,
    note: "Tile material spec reference for traceability; tile material remains excluded from labor pricing.",
  },
  {
    binding_code: "BIND_BATHROOM_FLOOR_TILE_30X60",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomFloorTileLabor,
    material_code: "TILE_30X60_FLOOR",
    role: "primary",
    is_default: true,
    requires_review: true,
    note: "Tile material spec reference for traceability; tile material remains excluded from labor pricing.",
  },
];

const pricingRules: PricingRule[] = [
  {
    price_rule_id: "price-rule-island-cabinet",
    quote_item_template_id: "qit-wood-island-cabinet",
    item_code: METHOD_SPEC_ITEM_CODES.islandCabinet,
    pricing_type: "fixed_unit_price",
    unit: "尺",
    unit_price: 3500,
    price_source: priceSource("spec-price-island-cabinet-001", "3500 / 尺"),
    confidence: 0.76,
    requires_review: false,
  },
  {
    price_rule_id: "price-rule-island-countertop",
    quote_item_template_id: "qit-wood-island-countertop",
    item_code: METHOD_SPEC_ITEM_CODES.islandCountertop,
    pricing_type: "fixed_unit_price",
    unit: "CM",
    unit_price: 180,
    price_source: priceSource("spec-price-island-countertop-001", "180 / CM"),
    confidence: 0.7,
    requires_review: false,
  },
  {
    price_rule_id: "price-rule-wardrobe-body",
    quote_item_template_id: "qit-wood-wardrobe-body",
    item_code: METHOD_SPEC_ITEM_CODES.wardrobeBody,
    pricing_type: "fixed_unit_price",
    unit: "尺",
    unit_price: 3200,
    price_source: priceSource("spec-price-wardrobe-body-001", "3200 / 尺"),
    confidence: 0.76,
    requires_review: false,
  },
  {
    price_rule_id: "price-rule-shoe-cabinet-body",
    quote_item_template_id: "qit-wood-shoe-cabinet-body",
    item_code: METHOD_SPEC_ITEM_CODES.shoeCabinetBody,
    pricing_type: "fixed_unit_price",
    unit: "尺",
    unit_price: 3000,
    price_source: priceSource("spec-price-shoe-cabinet-body-001", "3000 / 尺"),
    confidence: 0.76,
    requires_review: false,
  },
  {
    price_rule_id: "price-rule-bath-waterproof-h240",
    quote_item_template_id: "qit-masonry-bath-waterproof-h240",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWaterproof,
    pricing_type: "fixed_unit_price",
    unit: "間",
    unit_price: 12000,
    price_source: priceSource("spec-price-bath-waterproof-001", "12000 / 間"),
    confidence: 0.68,
    requires_review: false,
  },
  {
    price_rule_id: "price-rule-bath-wall-tile-labor",
    quote_item_template_id: "qit-masonry-bath-wall-tile-labor",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomWallTileLabor,
    pricing_type: "fixed_unit_price",
    unit: "式",
    unit_price: 18000,
    price_source: priceSource("spec-price-bath-wall-tile-001", "18000 / 式"),
    confidence: 0.54,
    requires_review: true,
    review_reason: "壁磚貼工仍需以實際壁面面積取代 mock 一式估算。",
  },
  {
    price_rule_id: "price-rule-bath-floor-tile-labor",
    quote_item_template_id: "qit-masonry-bath-floor-tile-labor",
    item_code: METHOD_SPEC_ITEM_CODES.bathroomFloorTileLabor,
    pricing_type: "fixed_unit_price",
    unit: "式",
    unit_price: 8000,
    price_source: priceSource("spec-price-bath-floor-tile-001", "8000 / 式"),
    confidence: 0.54,
    requires_review: true,
    review_reason: "地磚貼工仍需以實際地坪面積取代 mock 一式估算。",
  },
  {
    price_rule_id: "price-rule-socket-extension",
    quote_item_template_id: "qit-mep-socket-extension",
    item_code: METHOD_SPEC_ITEM_CODES.socketExtension,
    pricing_type: "fixed_unit_price",
    unit: "口",
    unit_price: 1800,
    price_source: priceSource("spec-price-socket-extension-001", "1800 / 口"),
    confidence: 0.72,
    requires_review: false,
  },
  {
    price_rule_id: "price-rule-lighting-install",
    quote_item_template_id: "qit-mep-lighting-install",
    item_code: METHOD_SPEC_ITEM_CODES.lightingInstall,
    pricing_type: "fixed_unit_price",
    unit: "盞",
    unit_price: 1200,
    price_source: priceSource("spec-price-lighting-install-001", "1200 / 盞"),
    confidence: 0.72,
    requires_review: false,
  },
  {
    price_rule_id: "price-rule-protection",
    quote_item_template_id: "qit-other-protection",
    item_code: METHOD_SPEC_ITEM_CODES.protection,
    pricing_type: "fixed_unit_price",
    unit: "式",
    unit_price: 15000,
    price_source: priceSource("spec-price-protection-001", "15000 / 式"),
    confidence: 0.58,
    requires_review: true,
    review_reason: "保護工程需依現場範圍確認。",
  },
  {
    price_rule_id: "price-rule-cleaning",
    quote_item_template_id: "qit-other-cleaning",
    item_code: METHOD_SPEC_ITEM_CODES.cleaning,
    pricing_type: "fixed_unit_price",
    unit: "式",
    unit_price: 8000,
    price_source: priceSource("spec-price-cleaning-001", "8000 / 式"),
    confidence: 0.58,
    requires_review: true,
    review_reason: "清潔工程需依完工狀態確認。",
  },
  {
    price_rule_id: "price-rule-management-fee",
    quote_item_template_id: "qit-other-management-fee",
    item_code: METHOD_SPEC_ITEM_CODES.managementFee,
    pricing_type: "percentage_of_subtotal",
    unit: "式",
    percentage_rate: 0.08,
    price_source: priceSource("spec-price-management-fee-001", "總工程款 8%"),
    confidence: 0.62,
    requires_review: true,
    review_reason: "工程管理費需確認專案管理範圍。",
  },
];

export const seedMethodSpecCatalog: MethodSpecCatalog = {
  catalog_id: "laibe-method-spec-catalog-v1",
  version: "0.2.9.1",
  quote_item_templates: quoteItemTemplates,
  method_recipes: methodRecipes,
  material_specs: materialSpecs,
  labor_rules: laborRules,
  note_templates: noteTemplates,
  unit_conversions: unitConversions,
  inclusion_exclusion_rules: inclusionExclusionRules,
  item_material_bindings: itemMaterialBindings,
  pricing_rules: pricingRules,
};
